[package]
name = "example"
version = "0.1.0"
authors = ["Denis Bourge <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
gdnative = { git = "https://github.com/GodotNativeTools/godot-rust" }

[lib]
crate-type = ["cdylib"]